# Generated by Django 3.0.4 on 2020-03-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200325_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='ig',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='link',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='pr',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='tell',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
